name: Richie Buchanan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060800'
    - '#a8a8a6'
    - '#52708c'
    - '#4e3a15'
    - '#839087'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
