name: Richie Buchanan
favicon: null
layout_spectrum: 0.40308978501707315
typography_spectrum: 0.6403116132132709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3d70c9'
    - '#f5ddc1'
    - '#b8a68e'
    - '#3c3c3e'
  brandStrength: 0.39771844539791346
  lightness: 0.4434279554989189
  saturation: 0.73204579600133
  rhythmicContrast: 0.6979665611870587
purpose: []
